version: '3'

services:
  app:
    image: node:lts
    container_name: app
    ports:
      - 3000:3000
    restart: always
    tty: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./src:/src
    working_dir: "/src"
    entrypoint: "npm run dev"